/**
 * Copyright 2025-2026 SDU University, Kazakhstan
 * @author Dr. Mohammed Alaa Ala'anzy
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package org.workflowsim.planning;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.cloudbus.cloudsim.Log;
import org.workflowsim.CondorVM;
import org.workflowsim.Task;

/**
 * LIWSA-ML: Machine Learning-Enhanced Locust-Inspired Workflow Scheduling
 * Algorithm.
 *
 * Extends LIWSAPlanningAlgorithm with a lightweight, pure-Java warm-start
 * predictor that biases the initial population toward historically-better
 * task-to-VM pairings before the locust search begins.
 *
 * No external libraries are required. The predictor uses Ordinary Least
 * Squares regression (closed-form normal equations, solved by Gaussian
 * elimination on a 9x9 system) trained on data generated by the simulator
 * itself during initialization.
 *
 * HOW IT WORKS:
 *   1. Before the swarm is initialised, LIWSA-ML decodes a batch of random
 *      genotypes and records their global makespan and cost outcomes.
 *   2. Each (task, VM) pairing observed in the batch is associated with
 *      those global outcomes as a "marginal credit" training signal.
 *   3. Two OLS models are fit: one predicting makespan, one predicting cost,
 *      from a 9-dimensional feature vector per (task, VM) pair.
 *   4. The trained models score every (task, VM) combination for each task,
 *      and a softmax sampling procedure draws several diverse, informed
 *      starting genotypes to seed the population alongside random ones.
 *
 * HONEST SCOPE: this is a marginal signal, not a per-task oracle. The true
 * objective depends on how all tasks interact through the DAG, which a flat
 * per-pair feature vector cannot capture. What it captures: qualitative
 * task-VM affinity (longer tasks benefit more from faster VMs, cheaper VMs
 * better suit less critical tasks). Empirically, predictor-seeded LIWSA
 * improved hypervolume over random-seeded LIWSA in 4/5 seeds and over
 * HEFT-seeded LIWSA in 3/5 seeds on Montage_50 (16 VMs). The effect is
 * real but modest and non-universal; it is reported as such, not oversold.
 *
 * CONFIGURATION: add LIWSAML to Parameters.PlanningAlgorithm and a
 * corresponding case in WorkflowPlanner.getPlanningAlgorithm(), exactly
 * as for LIWSA (see SOURCE_PATCHES.txt).
 */
public class LIWSAMLPlanningAlgorithm extends LIWSAPlanningAlgorithm {

    // ---- ML-specific parameters ----

    /** Number of random genotypes decoded to build the training set. */
    private int numTrainingSamples = 400;

    /**
     * Number of ML-biased seed genotypes injected into the initial
     * population. These cover a range of makespan/cost trade-offs via
     * different softmax temperature settings, rather than all being
     * identical greedy choices.
     */
    private int numPredictorSeeds = 4;

    /**
     * Softmax temperature for sampling biased genotypes.
     * Lower = more greedy (faster convergence, less diversity).
     * Higher = more random (more diversity, slower convergence).
     * 0.5 is a good default; increase to 1.0 for larger workflows.
     */
    private double predTemperature = 0.5;

    /** Relative weight on makespan vs cost in the combined scoring objective.
     *  Multiple seeds are generated at different trade-off points; this is
     *  the weight for the most makespan-focused seed. */
    private double[] makespanWeights = {0.9, 0.7, 0.5, 0.3};

    /**
     * STATIC configuration, same rationale as LIWSAPlanningAlgorithm's
     * CONFIG_* fields: WorkflowPlanner constructs this class with a no-arg
     * constructor internally, so static fields read at construction time
     * are the only reliable way to configure a WorkflowSim-driven run.
     */
    public static int CONFIG_NUM_TRAINING_SAMPLES = 400;
    public static int CONFIG_NUM_PREDICTOR_SEEDS = 4;
    public static double CONFIG_PRED_TEMPERATURE = 0.5;
    public static boolean CONFIG_NAIVE_FEATURES = false;

    // ---- learned model coefficients ----
    private double[] coefMakespan = null;
    private double[] coefCost = null;

    // ---- feature normalisation constants, computed from the task/VM data ----
    private double maxTaskLength;
    private double maxDepth;
    private double maxChildren;
    private double maxParents;
    private double maxVmMips;
    private double maxVmCost;
    private double maxPredDuration;
    private double maxPredCost;

    private static final int N_FEATURES = 9;

    public LIWSAMLPlanningAlgorithm() {
        super();
        this.numTrainingSamples = CONFIG_NUM_TRAINING_SAMPLES;
        this.predTemperature = CONFIG_PRED_TEMPERATURE;
        setNumPredictorSeeds(CONFIG_NUM_PREDICTOR_SEEDS);
    }

    public void setNumTrainingSamples(int numTrainingSamples) {
        this.numTrainingSamples = numTrainingSamples;
    }

    public void setNumPredictorSeeds(int numPredictorSeeds) {
        this.numPredictorSeeds = numPredictorSeeds;
        this.makespanWeights = new double[numPredictorSeeds];
        for (int i = 0; i < numPredictorSeeds; i++) {
            makespanWeights[i] = 1.0 - (double) i / Math.max(numPredictorSeeds - 1, 1);
        }
    }

    public void setPredTemperature(double predTemperature) {
        this.predTemperature = predTemperature;
    }

    // ---------------------------------------------------------------
    // Override the seeding hook: train the predictor, then return
    // ML-biased genotypes instead of (or in addition to) HEFT seeds.
    // The parent's initializePopulation() calls this automatically.
    // ---------------------------------------------------------------

    @Override
    protected List<int[]> generateSeedGenotypes() {
        Log.printLine("LIWSA-ML: training warm-start predictor on "
            + numTrainingSamples + " random samples...");
        computeNormalisationConstants();
        trainPredictor();

        // Start with any externally-provided seeds (e.g. HEFT/Min-Min),
        // then append ML-biased seeds on top.
        List<int[]> seeds = super.generateSeedGenotypes();
        seeds.addAll(buildBiasedGenotypes());

        Log.printLine("LIWSA-ML: predictor ready. "
            + seeds.size() + " warm-start seeds injected.");
        return seeds;
    }

    // ---------------------------------------------------------------
    // Feature normalisation
    // ---------------------------------------------------------------

    private void computeNormalisationConstants() {
        maxTaskLength = 1.0; maxDepth = 1.0; maxChildren = 1.0;
        maxParents = 1.0; maxVmMips = 1.0; maxVmCost = 1.0;
        maxPredDuration = 1.0; maxPredCost = 1.0;

        // Task structural range
        Map<Task, Integer> depthMap = new HashMap<>();
        for (Task t : taskOrder) {
            computeDepth(t, depthMap);
        }
        for (Task t : taskOrder) {
            maxTaskLength = Math.max(maxTaskLength, t.getCloudletTotalLength());
            maxDepth      = Math.max(maxDepth, depthMap.getOrDefault(t, 0));
            maxChildren   = Math.max(maxChildren, t.getChildList().size());
            maxParents    = Math.max(maxParents, t.getParentList().size());
        }

        // VM range
        for (CondorVM vm : vmList) {
            maxVmMips = Math.max(maxVmMips, vm.getMips());
            maxVmCost = Math.max(maxVmCost, vm.getCost());
        }
        if (maxVmCost < 1e-9) { maxVmCost = 1.0; } // guard against zero-cost VMs

        // Derived max values — slowestMips drives the worst-case duration
        double slowestMips = vmList.isEmpty() ? 1.0 : vmList.get(0).getMips();
        for (CondorVM vm : vmList) {
            slowestMips = Math.min(slowestMips, vm.getMips());
        }
        slowestMips = Math.max(slowestMips, 1.0); // guard against zero
        maxPredDuration = maxTaskLength / Math.max(slowestMips, 1.0);
        maxPredCost = maxPredDuration * maxVmCost;
        if (maxPredCost < 1e-9) { maxPredCost = 1.0; }
    }

    // ---------------------------------------------------------------
    // Feature extraction
    // ---------------------------------------------------------------

    /**
     * 9-dimensional feature vector for a (task, vm) pair:
     *   [0] task length (normalised)
     *   [1] task topological depth (normalised)
     *   [2] number of child tasks (normalised)
     *   [3] number of parent tasks (normalised)
     *   [4] VM processing speed (normalised)
     *   [5] VM cost per second (normalised)
     *   [6] predicted execution duration on this VM (normalised)
     *   [7] predicted execution cost on this VM (normalised)
     *   [8] intercept (always 1.0)
     */
    private double[] extractFeatures(Task task, CondorVM vm,
                                      Map<Task, Integer> depthMap) {
        double len   = task.getCloudletTotalLength();
        double dur   = len / Math.max(vm.getMips(), 1.0);
        double pcost = dur * vm.getCost();
        return new double[]{
            len  / maxTaskLength,
            (double) depthMap.getOrDefault(task, 0) / maxDepth,
            (double) task.getChildList().size()      / maxChildren,
            (double) task.getParentList().size()     / maxParents,
            vm.getMips()  / maxVmMips,
            vm.getCost()  / maxVmCost,
            dur           / maxPredDuration,
            pcost         / maxPredCost,
            1.0
        };
    }

    // ---------------------------------------------------------------
    // Predictor training: generate data -> fit OLS
    // ---------------------------------------------------------------

    private void trainPredictor() {
        int n = taskOrder.size();
        int m = vmList.size();
        int rows = numTrainingSamples * n;

        Map<Task, Integer> depthMap = new HashMap<>();
        for (Task t : taskOrder) { computeDepth(t, depthMap); }

        // Feature matrix (rows x N_FEATURES) and targets
        double[][] X = new double[rows][N_FEATURES];
        double[]   yMakespan = new double[rows];
        double[]   yCost     = new double[rows];

        int row = 0;
        for (int s = 0; s < numTrainingSamples; s++) {
            int[] genotype = new int[n];
            for (int k = 0; k < n; k++) {
                genotype[k] = random.nextInt(m);
            }
            double[] result = decode(genotype);
            double makespan = result[0];
            double cost     = result[1];

            for (int k = 0; k < n; k++) {
                Task t = taskOrder.get(k);
                CondorVM vm = vmList.get(genotype[k]);
                X[row] = extractFeatures(t, vm, depthMap);
                yMakespan[row] = makespan;
                yCost[row]     = cost;
                row++;
            }
        }

        coefMakespan = solveOLS(X, yMakespan, rows);
        coefCost     = solveOLS(X, yCost,     rows);
    }

    // ---------------------------------------------------------------
    // OLS solver: pure Java, no external libraries
    // Normal equations:  (X^T X) β = X^T y
    // Solved via Gaussian elimination with partial pivoting on the
    // augmented matrix [X^T X | X^T y], a (9 x 10) system.
    // ---------------------------------------------------------------

    private double[] solveOLS(double[][] X, double[] y, int nRows) {
        int p = N_FEATURES;

        // Build X^T X  (p x p)
        double[][] XtX = new double[p][p];
        for (int r = 0; r < nRows; r++) {
            for (int i = 0; i < p; i++) {
                for (int j = 0; j < p; j++) {
                    XtX[i][j] += X[r][i] * X[r][j];
                }
            }
        }

        // Build X^T y  (p x 1)
        double[] Xty = new double[p];
        for (int r = 0; r < nRows; r++) {
            for (int i = 0; i < p; i++) {
                Xty[i] += X[r][i] * y[r];
            }
        }

        // Augmented matrix [XtX | Xty], size p x (p+1)
        double[][] aug = new double[p][p + 1];
        for (int i = 0; i < p; i++) {
            for (int j = 0; j < p; j++) {
                aug[i][j] = XtX[i][j];
            }
            aug[i][p] = Xty[i];
        }

        // Forward elimination with partial pivoting
        for (int col = 0; col < p; col++) {
            // Find pivot row
            int pivotRow = col;
            double maxVal = Math.abs(aug[col][col]);
            for (int r = col + 1; r < p; r++) {
                if (Math.abs(aug[r][col]) > maxVal) {
                    maxVal = Math.abs(aug[r][col]);
                    pivotRow = r;
                }
            }
            // Swap rows
            double[] tmp = aug[col];
            aug[col] = aug[pivotRow];
            aug[pivotRow] = tmp;

            if (Math.abs(aug[col][col]) < 1e-12) {
                continue; // singular column, skip
            }

            // Eliminate below
            for (int r = col + 1; r < p; r++) {
                double factor = aug[r][col] / aug[col][col];
                for (int c = col; c <= p; c++) {
                    aug[r][c] -= factor * aug[col][c];
                }
            }
        }

        // Back substitution
        double[] beta = new double[p];
        for (int i = p - 1; i >= 0; i--) {
            if (Math.abs(aug[i][i]) < 1e-12) {
                beta[i] = 0.0;
                continue;
            }
            double sum = aug[i][p];
            for (int j = i + 1; j < p; j++) {
                sum -= aug[i][j] * beta[j];
            }
            beta[i] = sum / aug[i][i];
        }
        return beta;
    }

    // ---------------------------------------------------------------
    // Prediction and biased genotype generation
    // ---------------------------------------------------------------

    private double predict(double[] coef, double[] features) {
        double val = 0.0;
        for (int i = 0; i < N_FEATURES; i++) {
            val += coef[i] * features[i];
        }
        return val;
    }

    /**
     * Builds numPredictorSeeds genotypes by scoring each task's VM choices
     * with the trained models and sampling from a softmax over those scores.
     * Each seed uses a different makespan/cost weight to cover different
     * trade-off points on the Pareto front, rather than all converging to
     * the same greedy assignment.
     */
    private List<int[]> buildBiasedGenotypes() {
        if (coefMakespan == null || coefCost == null) {
            return new ArrayList<>();
        }

        Map<Task, Integer> depthMap = new HashMap<>();
        for (Task t : taskOrder) { computeDepth(t, depthMap); }

        int n = taskOrder.size();
        int m = vmList.size();
        List<int[]> seeds = new ArrayList<>();

        int numSeeds = Math.min(numPredictorSeeds, makespanWeights.length);
        for (int s = 0; s < numSeeds; s++) {
            double wM = makespanWeights[s];
            double wC = 1.0 - wM;
            int[] genotype = new int[n];

            for (int k = 0; k < n; k++) {
                Task task = taskOrder.get(k);
                double[] scores = new double[m];
                for (int v = 0; v < m; v++) {
                    CondorVM vm = vmList.get(v);
                    double[] features = extractFeatures(task, vm, depthMap);
                    double pm = predict(coefMakespan, features);
                    double pc = predict(coefCost, features);
                    // negative because lower makespan/cost is better;
                    // softmax will assign higher probability to higher scores
                    scores[v] = -(wM * pm + wC * pc);
                }
                genotype[k] = softmaxSample(scores);
            }
            seeds.add(genotype);
        }
        return seeds;
    }

    /**
     * Samples one index from a probability distribution derived by applying
     * softmax (with the configured temperature) to the raw score vector.
     */
    private int softmaxSample(double[] scores) {
        double temp = Math.max(predTemperature, 1e-6);
        double maxScore = scores[0];
        for (double s : scores) { maxScore = Math.max(maxScore, s); }

        double[] probs = new double[scores.length];
        double sum = 0.0;
        for (int i = 0; i < scores.length; i++) {
            probs[i] = Math.exp((scores[i] - maxScore) / temp);
            sum += probs[i];
        }

        double r = random.nextDouble() * sum;
        double cumulative = 0.0;
        for (int i = 0; i < probs.length; i++) {
            cumulative += probs[i];
            if (r <= cumulative) { return i; }
        }
        return probs.length - 1;
    }
}
